### ISSUE TITLE
Unable to use library in threads

### ISSUE THREAD

**Issue by svetlyak40wt** [svetlyak40wt/python-repr#1]
```
[2016-06-22 15:50:25,376] ERROR  : sentry.errors.serializer: 'local' object has no attribute 'processed'
Traceback (most recent call last):
  File "/usr/lib/yandex/yamb/env/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/usr/lib/yandex/yamb/env/lib/python2.7/site-packages/magic_repr/__init__.py", line 232, in method
    fields = list(starmap(serialize_text, fields))
  File "/usr/lib/yandex/yamb/env/lib/python2.7/site-packages/magic_repr/__init__.py", line 228, in <genexpr>
    fields = ((u'{0}='.format(name), value)
  File "/usr/lib/yandex/yamb/env/lib/python2.7/site-packages/magic_repr/__init__.py", line 225, in <genexpr>
    for name, getter in field_getters)
  File "/usr/lib/yandex/yamb/env/lib/python2.7/site-packages/magic_repr/__init__.py", line 125, in format_value
    if value_id in recursion_breaker.processed:
  File "/usr/lib/yandex/yamb/env/lib/python2.7/site-packages/gevent/local.py", line 181, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'local' object has no attribute 'processed'
```

**Comment by svetlyak40wt** [comment]
Fixed in 0.3.1.
